### PR TITLE
CLI: Launch APIs

### PR DESCRIPTION
**Pull request by dwhswenson**
- [x] `fah-alchemy api`
- [x] `fah-alchemy compute api`
- [x] tests for both

Seems to work when I run it locally, but I haven't quite got the testing figured out yet

@dotsdl : It would be useful if you could tell me which settings (if any) are relevant for each API launch. Then I'll add those as options.

### CODE REVIEW

**Comment by dotsdl** [comment]
Perhaps add one option to allow the JWT SECRET KEY to be generated on startup. This would just be a convenience for the single API service instance case; it would not be appropriate if launching many separate gunicorn instances.

**Comment by dotsdl** [comment]
Planning to hit this today @dwhswenson; anything additional I should know?

**Comment by dwhswenson** [comment]
There's probably some cleanup to be done here about getting the host URL / port from env vars as well; I can probably help with those parts, but we have a few things I'm focusing on from the OpenFE side for the next week (until board meeting).

Main issue is that I think your existing fixtures must mock out something that can't be pickled, and I couldn't trace down what that was. Without that, multiprocessing choking on the subprocess call.

**Comment by dotsdl** [comment]
@dwhswenson I believe the APIs now start up just fine with the tests. I noticed that they weren't dying properly, so the `test_api_application` test's service was sticking around by the time `test_api` would run. It doesn't look like this issue persists after my latest changes.

**Comment by dotsdl** [comment]
Would you mind wiring up env variables into the API CLI points? I've added the appropriate `*Settings` import into each point to indicate which one applies, and some pointers for how to inject these into the app in the user-facing API CLI entry point.

**Comment by dotsdl** [comment]
Thanks for doing this @dwhswenson! What you had was basically working already; very slick!

**Comment by dotsdl** [comment]
Looks like CI is just generally failing now, not just for this PR: https://github.com/openforcefield/fah-alchemy/actions/runs/3590301180

Unclear if this is due to changes on GHA that we'll have to find workarounds for, or if this is just some temporary condition that will resolve itself. Tests pass locally just fine in any case.

**Comment by dotsdl** [comment]
Think I fixed the tests; was due to the changes in `gufe` on tokenization. I've included my fixes here: https://github.com/OpenFreeEnergy/gufe/pull/102

**Comment by dotsdl** [comment]
Thanks @dwhswenson! This looks great; merging!

**Pull request merged**
