### PR TITLE
CLI : database init

### PR DESCRIPTION
**Pull request by dwhswenson**
Trying to scope these to relatively small incremental improvements; aiming that several small PRs in sequence might be easier to handle.

- [x] Add CLI command `fah-alchemy database init` to initialize a database
- [x] Tests for `fah-alchemy database init`

Part of #26.

### CODE REVIEW

**Comment by dwhswenson** [comment]
@dotsdl : I'm not sure if this is ready to merge yet, but it *is* ready for your eyes on it.

1. Is there any other functionality I should do in the database init? Should it create the DB if one can't be found at the URI?
2. What should the test of `database init` assert? So far it is a smoke test.

**Comment by dotsdl** [comment]
Working on this now @dwhswenson; making some quality of life improvements and bubbling these up to the CLI.

**Review by dotsdl — APPROVED** [review]
Just finished shuffling things around to match up with your work @dwhswenson! I'm happy with this, but if you want to give it a look before merge I'd be grateful.

**Review by dwhswenson — COMMENTED** [review]
LGTM! The only thing I would change is to make all the DB options reusable, the way I did with `DBNAME_OPTION`. That ensures consistent UX (option name, help, behavior) across different subcommands, and means that if you need to change a help string (e.g., to correct "URI" to "URL," which I need to do), you only need to do it once.

I'll make those changes in the follow-up PR that I'll be starting soon. Merge at will!

**Comment by dotsdl** [comment]
Excellent, thanks @dwhswenson! Yes, we'll definitely want the improvements you've proposed; I'll merge this one so we can build on it. Thanks again for setting us up here!

**Pull request merged**
